services:
  # Servicio de desarrollo
  autotrack-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "3000:3000"
    volumes:
      # Montar código fuente para hot reload
      - ./src:/app/src:cached
      - ./public:/app/public:cached
      - ./lib:/app/lib:cached
      # Configuración
      - ./next.config.ts:/app/next.config.ts:cached
      - ./tsconfig.json:/app/tsconfig.json:cached
      - ./postcss.config.mjs:/app/postcss.config.mjs:cached
      # Preservar node_modules en el contenedor
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    profiles:
      - dev
    networks:
      - autotrack-network

  # Servicio de producción
  autotrack-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    profiles:
      - prod
    networks:
      - autotrack-network
    restart: unless-stopped

networks:
  autotrack-network:
    driver: bridge
