'use client';
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traducciones
const translations = {
  es: {
    // Navbar
    'navbar.logout': 'Cerrar Sesión',
    
    // Sidebar
    'sidebar.home': 'Inicio',
    'sidebar.summary': 'Resumen',
    'sidebar.vehicles': 'Vehículos',
    'sidebar.movements': 'Movimientos',
    'sidebar.users': 'Usuarios',
    'sidebar.profile': 'Perfil',
    'sidebar.configuration': 'Configuración',
    'sidebar.roles': 'Roles',
    'sidebar.all': 'Todos',
    'sidebar.openMenu': 'Abrir menú',
    'sidebar.closeMenu': 'Cerrar menú',
    'sidebar.appName': 'SSM',
    'sidebar.adminPanel': 'Panel Admin',
    
    // Landing Page
    'landing.welcome': 'Bienvenido a Sena Security Mobile',
    'landing.login': 'Iniciar Sesión',
    'landing.register': 'Registrarse',
    'landing.tapToContinue': '(Toca para continuar)',
    'landing.title': 'SenaSecurityMobile',
    
    // Login
    'login.title': 'Iniciar Sesión',
    'login.email': 'Correo electrónico',
    'login.password': 'Contraseña',
    'login.submit': 'Iniciar Sesión',
    'login.noAccount': '¿No tienes cuenta?',
    'login.registerHere': 'Regístrate aquí',
    'login.noUsers': 'No hay usuarios registrados.',
    'login.success': 'Inicio de sesión exitoso.',
    'login.invalidCredentials': 'Credenciales incorrectas.',
    'login.emailPlaceholder': 'Correo electrónico',
    'login.passwordPlaceholder': 'Contraseña',
    'login.submitButton': 'Iniciar Sesión',
    'login.registerLink': 'Regístrate aquí',
    'login.imageAlt': 'Imagen de login',
    'login.noUsersError': 'No hay usuarios registrados.',
    'login.successMessage': 'Inicio de sesión exitoso.',
    
    // Register
    'register.title': 'Crear Cuenta',
    'register.name': 'Nombre completo',
    'register.document': 'Número de documento',
    'register.role': 'Selecciona un rol',
    'register.admin': 'Administrador',
    'register.user': 'Usuario',
    'register.email': 'Correo electrónico',
    'register.password': 'Contraseña',
    'register.confirmPassword': 'Confirmar contraseña',
    'register.submit': 'Registrarse',
    'register.hasAccount': '¿Ya tienes cuenta?',
    'register.loginHere': 'Inicia sesión',
    'register.passwordMismatch': 'Las contraseñas no coinciden.',
    'register.success': 'Registro exitoso. Ahora inicia sesión.',
    'register.uploadPhoto': 'Subir foto de perfil',
    'register.namePlaceholder': 'Nombre completo',
    'register.documentPlaceholder': 'Número de documento',
    'register.roleSelect': 'Selecciona un rol',
    'register.adminRole': 'Administrador',
    'register.userRole': 'Usuario',
    'register.emailPlaceholder': 'Correo electrónico',
    'register.passwordPlaceholder': 'Contraseña',
    'register.confirmPasswordPlaceholder': 'Confirmar contraseña',
    'register.submitButton': 'Registrarse',
    'register.loginLink': 'Inicia sesión',
    'register.imageAlt': 'Imagen de registro',
    'register.successMessage': 'Registro exitoso. Ahora inicia sesión.',
    
    // Dashboard
    'dashboard.title': 'Panel de Inicio',
    'dashboard.subtitle': 'Resumen rápido y accesos directos — colores suaves para una lectura cómoda.',
    'dashboard.totalUsers': 'Usuarios Totales',
    'dashboard.activeUsers': 'Activos',
    'dashboard.registeredToday': 'Registrados Hoy',
    'dashboard.registeredVehicles': 'Autos Registrados',
    'dashboard.vehiclesToday': 'Autos Registrados Hoy',
    'dashboard.quickAccess': 'Accesos Rápidos',
    'dashboard.profile': 'Perfil',
    'dashboard.profileDesc': 'Ver datos personales',
    'dashboard.settings': 'Configuración',
    'dashboard.settingsDesc': 'Opciones del sistema',
    'dashboard.vehicles': 'Vehículos',
    'dashboard.vehiclesDesc': 'Gestión de automóviles',
    'dashboard.searchUser': 'Buscar usuario...',
    'dashboard.name': 'Nombre',
    'dashboard.noUsers': 'No se encontraron usuarios.',
    'dashboard.homePanel': 'Panel de Inicio',
    'dashboard.quickSummary': 'Resumen rápido y accesos directos — colores suaves para una lectura cómoda.',
    'dashboard.totalUsersLabel': 'Usuarios Totales',
    'dashboard.activeLabel': 'Activos',
    'dashboard.registeredTodayLabel': 'Registrados Hoy',
    'dashboard.registeredCars': 'Autos Registrados',
    'dashboard.carsTodayLabel': 'Autos Registrados Hoy',
    'dashboard.quickAccessTitle': 'Accesos Rápidos',
    'dashboard.profileTitle': 'Perfil',
    'dashboard.profileDescription': 'Ver datos personales',
    'dashboard.configurationTitle': 'Configuración',
    'dashboard.configurationDescription': 'Opciones del sistema',
    'dashboard.vehiclesTitle': 'Vehículos',
    'dashboard.vehiclesDescription': 'Gestión de automóviles',
    'dashboard.searchPlaceholder': 'Buscar usuario...',
    'dashboard.nameColumn': 'Nombre',
    'dashboard.noUsersFound': 'No se encontraron usuarios.',
    
    // Movements
    'movements.title': 'Registro de Movimientos',
    'movements.registerNew': '🚗 Registrar nuevo movimiento',
    'movements.platePlaceholder': 'Placa del vehículo',
    'movements.entry': 'Entrada',
    'movements.exit': 'Salida',
    'movements.history': '🧾 Historial de Movimientos',
    'movements.plate': 'Placa',
    'movements.type': 'Tipo',
    'movements.time': 'Hora',
    'movements.date': 'Fecha',
    'movements.noMovements': 'No hay movimientos registrados aún.',
    'movements.invalidPlate': 'Ingresa una placa válida',
    'movements.entrance': 'Entrada',
    'movements.exitType': 'Salida',
    
    // Vehicles
    'vehicles.title': 'Registrar Vehículo',
    'vehicles.pageTitle': 'Registrar Vehículo',
    'vehicles.editTitle': '✏️ Editar Vehículo',
    'vehicles.subtitle': 'Gestiona las placas de tu parqueadero de forma simple.',
    'vehicles.searchPlaceholder': 'Buscar por nombre, placa o tipo...',
    'vehicles.exportCSV': 'Exportar CSV',
    'vehicles.manualMode': 'Manual',
    'vehicles.autoMode': 'Automático',
    'vehicles.ownerName': 'Nombre del propietario',
    'vehicles.ownerPlaceholder': 'Nombre del propietario',
    'vehicles.plate': 'Placa',
    'vehicles.platePlaceholder': 'Placa (ej: ABC-123)',
    'vehicles.type': 'Tipo de vehículo',
    'vehicles.car': 'Carro',
    'vehicles.motorcycle': 'Moto',
    'vehicles.bicycle': 'Bicicleta',
    'vehicles.typeCar': 'Carro',
    'vehicles.typeMotorcycle': 'Moto',
    'vehicles.typeBicycle': 'Bicicleta',
    'vehicles.register': 'Registrar',
    'vehicles.registerAuto': 'Registrar (Automático)',
    'vehicles.changeToManual': 'Cambiar a Manual',
    'vehicles.saveChanges': 'Guardar cambios',
    'vehicles.cancel': 'Cancelar',
    'vehicles.registered': 'Vehículos Registrados',
    'vehicles.registeredList': 'Vehículos Registrados',
    'vehicles.noVehicles': 'No hay vehículos aún.',
    'vehicles.noMatches': 'No hay vehículos que coincidan.',
    'vehicles.edit': 'Editar',
    'vehicles.delete': 'Eliminar',
    'vehicles.deleteConfirm': '¿Eliminar vehículo? Esta acción no se puede deshacer.',
    'vehicles.total': 'total',
    'vehicles.clearList': 'Vaciar lista',
    'vehicles.listCleared': 'Lista vaciada',
    'vehicles.cameraStarted': 'Cámara iniciada (modo automático)',
    'vehicles.cameraError': 'No se pudo acceder a la cámara (revisa permisos)',
    'vehicles.browserNotSupported': 'Tu navegador no soporta getUserMedia',
    'vehicles.nameRequired': 'El nombre es obligatorio',
    'vehicles.invalidPlate': 'Placa inválida (solo letras, números y guiones, 3-8 caracteres)',
    'vehicles.duplicatePlate': 'Ya existe un vehículo con esa placa',
    'vehicles.vehicleUpdated': 'Vehículo actualizado',
    'vehicles.vehicleRegistered': 'Vehículo registrado',
    'vehicles.vehicleDeleted': 'Vehículo eliminado',
    'vehicles.vehicleRegisteredAuto': 'Vehículo registrado (modo automático)',
    'vehicles.cameraNotStarted': 'Cámara no iniciada',
    'vehicles.missingApiKey': 'Falta la clave de Plate Recognizer. Define NEXT_PUBLIC_PLATE_API_KEY',
    'vehicles.capturingImage': 'Capturando imagen...',
    'vehicles.sendingRecognition': 'Enviando a reconocimiento...',
    'vehicles.plateDetected': 'Placa detectada',
    'vehicles.noPlateDetected': 'No se detectó placa en la imagen',
    'vehicles.recognitionError': 'Error en reconocimiento',
    'vehicles.processing': 'Procesando...',
    'vehicles.captureAndRecognize': 'Capturar y reconocer',
    'vehicles.stopCamera': 'Detener cámara',
    'vehicles.confidence': 'Confianza',
    'vehicles.noVehiclesToExport': 'No hay vehículos para exportar',
    'vehicles.captureError': 'Error al capturar imagen',
    
    // Users Page
    'users.title': 'Administración de Usuarios',
    'users.subtitle': 'Lista de usuarios registrados — ver, editar o eliminar.',
    'users.searchPlaceholder': 'Buscar por nombre, email o documento...',
    'users.searchLabel': 'Buscar usuarios',
    'users.nameColumn': 'Nombre',
    'users.emailColumn': 'Correo',
    'users.documentColumn': 'Documento',
    'users.roleColumn': 'Rol',
    'users.actionsColumn': 'Acciones',
    'users.noUsersFound': 'No se encontraron usuarios.',
    'users.userRole': 'usuario',
    'users.deleteConfirm': '¿Eliminar este usuario? Esta acción no se puede deshacer.',
    'users.userDeleted': 'Usuario eliminado.',
    'users.editUser': 'Editar usuario',
    'users.userDetails': 'Detalle de usuario',
    'users.close': 'Cerrar ✕',
    'users.name': 'Nombre',
    'users.email': 'Email',
    'users.document': 'Documento',
    'users.role': 'Rol',
    'users.registeredAt': 'Registrado',
    'users.edit': 'Editar',
    'users.delete': 'Eliminar',
    'users.nameRequired': 'Nombre y correo son obligatorios.',
    'users.changesSaved': 'Cambios guardados.',
    'users.cancel': 'Cancelar',
    'users.save': 'Guardar',
    'users.rolePlaceholder': 'usuario / admin',
    
    // Summary Page
    'summary.welcomeUser': '¡Bienvenido, Nicolás!',
    'summary.todayDate': 'Hoy es',
    'summary.entriesTitle': 'Entradas hoy',
    'summary.exitsTitle': 'Salidas hoy',
    'summary.totalTitle': 'Total movimientos',
    'summary.weeklyReportTitle': 'Reporte semanal',
    'summary.lastMovementsTitle': 'Últimos movimientos',
    'summary.noMovementsMessage': 'No hay movimientos aún.',
    'summary.darkModeActive': 'Modo oscuro activo',
    'summary.lightModeActive': 'Modo claro',
    
    // Días de la semana
    'days.sun': 'Dom',
    'days.mon': 'Lun',
    'days.tue': 'Mar',
    'days.wed': 'Mié',
    'days.thu': 'Jue',
    'days.fri': 'Vie',
    'days.sat': 'Sáb',
    
    // Configuración
    'config.title': 'Configuración',
    'config.subtitle': 'Personaliza tu perfil y configura las preferencias del sistema',
    'config.profile': 'Datos del Perfil',
    'config.language': 'Configuración de Idioma',
    'config.name': 'Nombre',
    'config.email': 'Correo Electrónico',
    'config.document': 'Documento',
    'config.role': 'Rol',
    'config.currentLang': 'Idioma Actual',
    'config.selectLang': 'Seleccionar Idioma',
    'config.spanish': 'Español',
    'config.english': 'Inglés',
    'config.saveProfile': 'Guardar Perfil',
    'config.success': 'Configuración guardada exitosamente',
    'config.error': 'Error al guardar la configuración',
    'config.theme': 'Tema',
    'config.darkMode': 'Modo Oscuro',
    'config.lightMode': 'Modo Claro',
    'config.auto': 'Automático',
    'config.systemInfo': 'Información del Sistema',
    'config.version': 'Versión',
    'config.framework': 'Framework',
    'config.status': 'Estado',
    'config.active': 'Activo',
    'config.autoSave': 'El idioma se cambia automáticamente y se guarda para futuras sesiones.',
    'config.saving': 'Guardando...',
    'config.namePlaceholder': 'Ingresa tu nombre completo',
    'config.emailPlaceholder': 'correo@ejemplo.com',
    'config.documentPlaceholder': 'Número de documento',
    
    // VehicleModal
    'vehicleModal.title': 'Registrar Vehículo',
    'vehicleModal.ownerName': 'Nombre del dueño',
    'vehicleModal.plate': 'Placa',
    'vehicleModal.vehicleType': 'Tipo de vehículo',
    'vehicleModal.car': 'Carro',
    'vehicleModal.motorcycle': 'Moto',
    'vehicleModal.bicycle': 'Bicicleta',
    'vehicleModal.cancel': 'Cancelar',
    'vehicleModal.save': 'Guardar',
    
    // Formularios generales
    'form.required': 'Este campo es requerido',
    'form.loading': 'Cargando...',
    'form.success': 'Operación exitosa',
    'form.error': 'Error en la operación',

    //perfil
    'profile.title': 'Perfil',
    'profile.nameLabel': 'Nombre completo',
    'profile.emailLabel': 'Correo electrónico',
    'profile.documentLabel': 'Documento de identidad',
    'profile.noData': 'No hay datos de usuario',
    'profile.loading': 'Cargando datos del perfil...',
    'profile.logout': 'Cerrar sesión',
    
    // Theme Toggle
    'theme.light': 'Modo claro',
    'theme.dark': 'Modo oscuro',
    'theme.toggleTo': 'Cambiar a',
  },
  en: {
    // Navbar
    'navbar.logout': 'Logout',
    
    // Sidebar
    'sidebar.home': 'Home',
    'sidebar.summary': 'Summary',
    'sidebar.vehicles': 'Vehicles',
    'sidebar.movements': 'Movements',
    'sidebar.users': 'Users',
    'sidebar.profile': 'Profile',
    'sidebar.configuration': 'Settings',
    'sidebar.roles': 'Roles',
    'sidebar.all': 'All',
    'sidebar.openMenu': 'Open menu',
    'sidebar.closeMenu': 'Close menu',
    'sidebar.appName': 'SSM',
    'sidebar.adminPanel': 'Admin Panel',
    
    // Landing Page
    'landing.welcome': 'Welcome to Sena Security Mobile',
    'landing.login': 'Sign In',
    'landing.register': 'Sign Up',
    'landing.tapToContinue': '(Tap to continue)',
    'landing.title': 'SenaSecurityMobile',
    
    // Login
    'login.title': 'Sign In',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.noAccount': "Don't have an account?",
    'login.registerHere': 'Sign up here',
    'login.noUsers': 'No registered users.',
    'login.success': 'Login successful.',
    'login.invalidCredentials': 'Invalid credentials.',
    'login.emailPlaceholder': 'Email address',
    'login.passwordPlaceholder': 'Password',
    'login.submitButton': 'Sign In',
    'login.registerLink': 'Sign up here',
    'login.imageAlt': 'Login image',
    'login.noUsersError': 'No registered users.',
    'login.successMessage': 'Login successful.',
    
    // Register
    'register.title': 'Create Account',
    'register.name': 'Full name',
    'register.document': 'Document number',
    'register.role': 'Select a role',
    'register.admin': 'Administrator',
    'register.user': 'User',
    'register.email': 'Email address',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm password',
    'register.submit': 'Sign Up',
    'register.hasAccount': 'Already have an account?',
    'register.loginHere': 'Sign in',
    'register.passwordMismatch': 'Passwords do not match.',
    'register.success': 'Registration successful. Please sign in.',
    'register.uploadPhoto': 'Upload profile photo',
    'register.namePlaceholder': 'Full name',
    'register.documentPlaceholder': 'Document number',
    'register.roleSelect': 'Select a role',
    'register.adminRole': 'Administrator',
    'register.userRole': 'User',
    'register.emailPlaceholder': 'Email address',
    'register.passwordPlaceholder': 'Password',
    'register.confirmPasswordPlaceholder': 'Confirm password',
    'register.submitButton': 'Sign Up',
    'register.loginLink': 'Sign in',
    'register.imageAlt': 'Registration image',
    'register.successMessage': 'Registration successful. Please sign in.',
    
    // Dashboard
    'dashboard.title': 'Home Panel',
    'dashboard.subtitle': 'Quick overview and shortcuts — soft colors for comfortable reading.',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.activeUsers': 'Active',
    'dashboard.registeredToday': 'Registered Today',
    'dashboard.registeredVehicles': 'Registered Cars',
    'dashboard.vehiclesToday': 'Cars Registered Today',
    'dashboard.quickAccess': 'Quick Access',
    'dashboard.profile': 'Profile',
    'dashboard.profileDesc': 'View personal data',
    'dashboard.settings': 'Settings',
    'dashboard.settingsDesc': 'System options',
    'dashboard.vehicles': 'Vehicles',
    'dashboard.vehiclesDesc': 'Vehicle management',
    'dashboard.searchUser': 'Search user...',
    'dashboard.name': 'Name',
    'dashboard.noUsers': 'No users found.',
    'dashboard.homePanel': 'Home Panel',
    'dashboard.quickSummary': 'Quick overview and shortcuts — soft colors for comfortable reading.',
    'dashboard.totalUsersLabel': 'Total Users',
    'dashboard.activeLabel': 'Active',
    'dashboard.registeredTodayLabel': 'Registered Today',
    'dashboard.registeredCars': 'Registered Cars',
    'dashboard.carsTodayLabel': 'Cars Registered Today',
    'dashboard.quickAccessTitle': 'Quick Access',
    'dashboard.profileTitle': 'Profile',
    'dashboard.profileDescription': 'View personal data',
    'dashboard.configurationTitle': 'Settings',
    'dashboard.configurationDescription': 'System options',
    'dashboard.vehiclesTitle': 'Vehicles',
    'dashboard.vehiclesDescription': 'Vehicle management',
    'dashboard.searchPlaceholder': 'Search user...',
    'dashboard.nameColumn': 'Name',
    'dashboard.noUsersFound': 'No users found.',
    
    // Movements
    'movements.title': 'Movement Registration',
    'movements.registerNew': '🚗 Register new movement',
    'movements.platePlaceholder': 'Vehicle plate',
    'movements.entry': 'Entry',
    'movements.exit': 'Exit',
    'movements.history': '🧾 Movement History',
    'movements.plate': 'Plate',
    'movements.type': 'Type',
    'movements.time': 'Time',
    'movements.date': 'Date',
    'movements.noMovements': 'No movements registered yet.',
    'movements.invalidPlate': 'Enter a valid plate',
    'movements.entrance': 'Entry',
    'movements.exitType': 'Exit',
    
    // Vehicles
    'vehicles.title': 'Register Vehicle',
    'vehicles.pageTitle': 'Register Vehicle',
    'vehicles.editTitle': '✏️ Edit Vehicle',
    'vehicles.subtitle': 'Manage your parking lot plates simply.',
    'vehicles.searchPlaceholder': 'Search by name, plate or type...',
    'vehicles.exportCSV': 'Export CSV',
    'vehicles.manualMode': 'Manual',
    'vehicles.autoMode': 'Automatic',
    'vehicles.ownerName': 'Owner name',
    'vehicles.ownerPlaceholder': 'Owner name',
    'vehicles.plate': 'Plate',
    'vehicles.platePlaceholder': 'License plate (ex: ABC-123)',
    'vehicles.type': 'Vehicle type',
    'vehicles.car': 'Car',
    'vehicles.motorcycle': 'Motorcycle',
    'vehicles.bicycle': 'Bicycle',
    'vehicles.typeCar': 'Car',
    'vehicles.typeMotorcycle': 'Motorcycle',
    'vehicles.typeBicycle': 'Bicycle',
    'vehicles.register': 'Register',
    'vehicles.registerAuto': 'Register (Automatic)',
    'vehicles.changeToManual': 'Change to Manual',
    'vehicles.saveChanges': 'Save changes',
    'vehicles.cancel': 'Cancel',
    'vehicles.registered': 'Registered Vehicles',
    'vehicles.registeredList': 'Registered Vehicles',
    'vehicles.noVehicles': 'No vehicles yet.',
    'vehicles.noMatches': 'No matching vehicles.',
    'vehicles.edit': 'Edit',
    'vehicles.delete': 'Delete',
    'vehicles.deleteConfirm': 'Delete vehicle? This action cannot be undone.',
    'vehicles.total': 'total',
    'vehicles.clearList': 'Clear list',
    'vehicles.listCleared': 'List cleared',
    'vehicles.cameraStarted': 'Camera started (automatic mode)',
    'vehicles.cameraError': 'Could not access camera (check permissions)',
    'vehicles.browserNotSupported': 'Your browser does not support getUserMedia',
    'vehicles.nameRequired': 'Name is required',
    'vehicles.invalidPlate': 'Invalid plate (letters, numbers and dashes only, 3-8 characters)',
    'vehicles.duplicatePlate': 'A vehicle with that plate already exists',
    'vehicles.vehicleUpdated': 'Vehicle updated',
    'vehicles.vehicleRegistered': 'Vehicle registered',
    'vehicles.vehicleDeleted': 'Vehicle deleted',
    'vehicles.vehicleRegisteredAuto': 'Vehicle registered (automatic mode)',
    'vehicles.cameraNotStarted': 'Camera not started',
    'vehicles.missingApiKey': 'Missing Plate Recognizer key. Define NEXT_PUBLIC_PLATE_API_KEY',
    'vehicles.capturingImage': 'Capturing image...',
    'vehicles.sendingRecognition': 'Sending for recognition...',
    'vehicles.plateDetected': 'Plate detected',
    'vehicles.noPlateDetected': 'No plate detected in image',
    'vehicles.recognitionError': 'Recognition error',
    'vehicles.processing': 'Processing...',
    'vehicles.captureAndRecognize': 'Capture and recognize',
    'vehicles.stopCamera': 'Stop camera',
    'vehicles.confidence': 'Confidence',
    'vehicles.noVehiclesToExport': 'No vehicles to export',
    'vehicles.captureError': 'Error capturing image',
    
    // Users Page
    'users.title': 'User Management',
    'users.subtitle': 'List of registered users — view, edit or delete.',
    'users.searchPlaceholder': 'Search by name, email or document...',
    'users.searchLabel': 'Search users',
    'users.nameColumn': 'Name',
    'users.emailColumn': 'Email',
    'users.documentColumn': 'Document',
    'users.roleColumn': 'Role',
    'users.actionsColumn': 'Actions',
    'users.noUsersFound': 'No users found.',
    'users.userRole': 'user',
    'users.deleteConfirm': 'Delete this user? This action cannot be undone.',
    'users.userDeleted': 'User deleted.',
    'users.editUser': 'Edit user',
    'users.userDetails': 'User details',
    'users.close': 'Close ✕',
    'users.name': 'Name',
    'users.email': 'Email',
    'users.document': 'Document',
    'users.role': 'Role',
    'users.registeredAt': 'Registered',
    'users.edit': 'Edit',
    'users.delete': 'Delete',
    'users.nameRequired': 'Name and email are required.',
    'users.changesSaved': 'Changes saved.',
    'users.cancel': 'Cancel',
    'users.save': 'Save',
    'users.rolePlaceholder': 'user / admin',
    
    // Summary Page
    'summary.welcomeUser': 'Welcome, Nicolás!',
    'summary.todayDate': 'Today is',
    'summary.entriesTitle': 'Entries today',
    'summary.exitsTitle': 'Exits today',
    'summary.totalTitle': 'Total movements',
    'summary.weeklyReportTitle': 'Weekly report',
    'summary.lastMovementsTitle': 'Latest movements',
    'summary.noMovementsMessage': 'No movements yet.',
    'summary.darkModeActive': 'Dark mode active',
    'summary.lightModeActive': 'Light mode',
    
    // Días de la semana
    'days.sun': 'Sun',
    'days.mon': 'Mon',
    'days.tue': 'Tue',
    'days.wed': 'Wed',
    'days.thu': 'Thu',
    'days.fri': 'Fri',
    'days.sat': 'Sat',
    
    // Configuración
    'config.title': 'Settings',
    'config.subtitle': 'Customize your profile and configure system preferences',
    'config.profile': 'Profile Data',
    'config.language': 'Language Settings',
    'config.name': 'Name',
    'config.email': 'Email',
    'config.document': 'Document',
    'config.role': 'Role',
    'config.currentLang': 'Current Language',
    'config.selectLang': 'Select Language',
    'config.spanish': 'Spanish',
    'config.english': 'English',
    'config.saveProfile': 'Save Profile',
    'config.success': 'Settings saved successfully',
    'config.error': 'Error saving settings',
    'config.theme': 'Theme',
    'config.darkMode': 'Dark Mode',
    'config.lightMode': 'Light Mode',
    'config.auto': 'Auto',
    'config.systemInfo': 'System Information',
    'config.version': 'Version',
    'config.framework': 'Framework',
    'config.status': 'Status',
    'config.active': 'Active',
    'config.autoSave': 'Language changes automatically and is saved for future sessions.',
    'config.saving': 'Saving...',
    'config.namePlaceholder': 'Enter your full name',
    'config.emailPlaceholder': 'email@example.com',
    'config.documentPlaceholder': 'Document number',
    
    // VehicleModal
    'vehicleModal.title': 'Register Vehicle',
    'vehicleModal.ownerName': 'Owner name',
    'vehicleModal.plate': 'License plate',
    'vehicleModal.vehicleType': 'Vehicle type',
    'vehicleModal.car': 'Car',
    'vehicleModal.motorcycle': 'Motorcycle',
    'vehicleModal.bicycle': 'Bicycle',
    'vehicleModal.cancel': 'Cancel',
    'vehicleModal.save': 'Save',
    
    // Formularios generales
    'form.required': 'This field is required',
    'form.loading': 'Loading...',
    'form.success': 'Operation successful',
    'form.error': 'Operation error',

    //profile
    'profile.title': 'Profile',
    'profile.nameLabel': 'Full name',
    'profile.emailLabel': 'Email',
    'profile.documentLabel': 'Identity document',
    'profile.noData': 'No user data available',
    'profile.loading': 'Loading profile data...',
    'profile.logout': 'Logout',
    
    // Theme Toggle
    'theme.light': 'Light mode',
    'theme.dark': 'Dark mode',
    'theme.toggleTo': 'Switch to',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'es' || savedLang === 'en')) {
      setLanguage(savedLang);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
